### PR TITLE
change in the Declaration of variable i in stream_t::accept_tcp()

### PR DESCRIPTION
**Pull request by joscollin**
Hello,

I have done a fix for the declaration of the variable i in stream_t::accept_tcp() in reass/demo/reass_printall.cpp. This gives a compile time error as the declaration is not within the scope. Please review it and let me know. If the fix is good, please give me the write access to merge.

Regards,
Jos Collin

### CODE REVIEW

**Comment by weary** [comment]
Hi,

Thanks for your interest in this project, but could you explain your patch a bit more? What compiler did you use to get this error?
That variable 'i' should be in local scope, not in class scope, as it is only valid within that while-loop.

Thanks in advance for explaining

**Comment by joscollin** [comment]
I was using g++ in RHEL 6.7.
# g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

But it is not a compiler version issue.

>  That variable 'i' should be in local scope, not in class scope, as it is only valid within that while-loop.
I was a little bit confused about your logic. In your code, as the variable 'i' appears in both 'if' and 'else' clauses, I have made it in the class scope to avoid the errors. But If it is supposed to be in the local scope, then to avoid compilation errors, you have to put it outside the if-else. This makes the 'i' available in both if and else clauses. Please check your code, the 'i' is not declared inside the else case ! 

Also let me know how you want me to fix it, local or class scope.

Thanks & Regards,
Jos Collin

**Comment by weary** [comment]
Ah!
Sorry, I merged a pull request, but somehow failed to apply it locally, so it compiled just fine for me :). Looks like the fix to print out null-bytes contained a bug (which you found).

That line in the 'else' branch should not contain the '.substr(0, i)', looks like a copy-paste. So:
`std::cout << d_prefix <<": " << d_data.substr(0, i) << std::endl;`
should just be:
`std::cout << d_prefix <<": " << d_data << std::endl;`

Could you make a pull request for something like that, or would you like me to do it?

**Comment by joscollin** [comment]
Okay, Thanks for the clarification. I will do it and push it right now. Could you please give me a merge access ?

**Comment by weary** [comment]
Thanks!
I merged it

**Comment by joscollin** [comment]
Hi,

When I build with boost version 1.41.0, I get the following errors. What 
is the minimum version of boost can be used with reass ?

Please let me know.
Thanks,
Jos Collin

[root@jos-01759382 reass-master]# make
[ 50%] Built target libreass
[ 56%] Built target pcap_manual_reorder
[ 62%] Built target reass_monitor_packetloss
[ 68%] Built target reass_printall
[ 75%] Built target reass_speedtest
[ 81%] Building CXX object 
testcases/CMakeFiles/unittest.dir/test_refpcap.cpp.o
/home/jcollin/reass-master/testcases/test_refpcap.cpp:4:31: error: 
boost/uuid/sha1.hpp: No such file or directory
/home/jcollin/reass-master/testcases/test_refpcap.cpp:7: error: 
‘boost::uuids’ has not been declared
/home/jcollin/reass-master/testcases/test_refpcap.cpp:9: error: 
‘std::string to_str’ redeclared as different kind of symbol
/home/jcollin/reass-master/./reass/helpers/misc.h:39: error: previous 
declaration of ‘template<class T> std::string to_str(const T&)’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:9: error: ‘sha1’ 
was not declared in this scope
/home/jcollin/reass-master/testcases/test_refpcap.cpp:9: error: ‘hash’ 
was not declared in this scope
/home/jcollin/reass-master/testcases/test_refpcap.cpp: In member 
function ‘void hashing_listener_t::finish(tcp_stream_t*)’:
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: ‘sha1’ 
was not declared in this scope
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: ‘sha’ 
was not declared in this scope
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: 
expected type-specifier before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: 
expected ‘>’ before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: 
expected ‘(’ before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: 
expected primary-expression before ‘>’ token
/home/jcollin/reass-master/testcases/test_refpcap.cpp:29: error: 
expected ‘)’ before ‘;’ token
/home/jcollin/reass-master/testcases/test_refpcap.cpp: In member 
function ‘virtual void hashing_listener_t::accept_tcp(packet_t*, int, 
tcp_stream_t*)’:
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: ‘sha1’ 
was not declared in this scope
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: ‘sha’ 
was not declared in this scope
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: 
expected type-specifier before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: 
expected ‘>’ before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: 
expected ‘(’ before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: 
expected primary-expression before ‘>’ token
/home/jcollin/reass-master/testcases/test_refpcap.cpp:52: error: 
expected ‘)’ before ‘;’ token
/home/jcollin/reass-master/testcases/test_refpcap.cpp:55: error: 
expected type-specifier before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:55: error: 
expected ‘;’ before ‘sha1’
/home/jcollin/reass-master/testcases/test_refpcap.cpp:70: error: type 
‘<type error>’ argument given to ‘delete’, expected pointer
make[2]: *** [testcases/CMakeFiles/unittest.dir/test_refpcap.cpp.o] Error 1
make[1]: *** [testcases/CMakeFiles/unittest.dir/all] Error 2
make: *** [all] Error 2

**Comment by weary** [comment]
Boost 1.48 was tested and found buggy
Boost 1.49 and newer should work
Some boost versions before 1.48 might work
Please note that I do not keep around buildhosts for old platforms, so even though these boost versions used to work, they might not anymore.

You could try to remove the test_refpcap from testcases/CMakeLists.txt, as only that testcase depends on  boost's uuid library (which was introduced in boost 1.42)

**Comment by joscollin** [comment]
On Wednesday 21 December 2016 12:59 AM, weary wrote:
>
> Boost 1.48 was tested and found buggy
> Boost 1.49 and newer should work
> Some boost versions before 1.48 might work
> Please note that I do not keep around buildhosts for old platforms, so 
> even though these boost versions used to work, they might not anymore.
>
I have found that the uuid introduced in Boost Version 1.42.0. So 
anything before that won't work for testcases.

> You could try to remove the test_refpcap from 
> testcases/CMakeLists.txt, as only that testcase depends on boost's 
> uuid library (which was introduced in boost 1.42)
>
That's what I did as a solution.


It looks like my push is not merged yet. In my fork it still shows "Able 
to Merge". Please see the screenshot in the attachment. It is the 
difference between my master and your master branches !

Thanks,
Jos Collin

**Comment by weary** [comment]
Hi,
I cannot find your screenshot, and github does not show any pull requests anymore, so on my end it looks like your commit is in the repo.
I did squash your three commits into one, perhaps that is why your fork still shows that button?

Regards

**Comment by joscollin** [comment]
I'm not sure. I did the first push and created a Pull Request, which I 
closed by accident. Then I did a second Push and created another Pull 
Request. Then i did the third Push and did not create a Pull Request, 
seeing that one is already there.

Screenshot is here: http://prntscr.com/dm0mh8

I think I will create one more Pull Request (the third one) and then you 
can merge, which will solve the problem.

Thanks,
Jos Collin

irc: *JosCollin*
☎ *+91-953-879-3925*
